### ISSUE TITLE
System Audio Mode Request should be 0x7d

### ISSUE THREAD

**Issue by SzymonSlupik** [tsowell/avr-hdmi-cec-volume#4]
```
case 0x70:
#ifdef DEBUG
					/* System Audio Mode Request */
					printf_P(PSTR("<sys audio>\n"));
#endif /* DEBUG */
					_delay_ms(13);
					set_system_audio_mode(ADDRESS, 0x0f, 1);
					break;
```

should (most likely) be
```
case 0x7d:
#ifdef DEBUG
					/* System Audio Mode Request */
					printf_P(PSTR("<sys audio>\n"));
#endif /* DEBUG */
					_delay_ms(13);
					set_system_audio_mode(ADDRESS, 0x0f, 1);
					break;
```

**Comment by tsowell** [comment]
I think 0x70 is correct here, but it's hard to keep track of the different "Audio Mode" CEC messages because the names are so similar.

Based on my reading of the CEC spec, 0x70 is System Audio Mode Request, and the code is correct in responding with a Set System Audio Mode (0x72) message.

0x7d is a different message, Give System Audio Mode Status.  The initiator expects a System Audio Mode Status (0x7e) message in response.  I never added support for this because my devices don't require it, but I think 124de90 (which I haven't tested) adds correct support for this message.

Does all that look correct to you?

**Comment by tsowell** [comment]
Thanks for testing this and responding in the commit.  I'll see if my TV is happy with 0x72 in response to 0x7d, but I may #ifdef this anyway because it seems to differ from the spec.  I'll leave the issue open until then.

**Comment by SzymonSlupik** [comment]
So according to this (for example): [http://www.andrewncarr.com/hdmi/hdmi-cec-codes.xls](http://www.andrewncarr.com/hdmi/hdmi-cec-codes.xls), 
```
If device does not <Feature Abort> the following message:
   <Give System Audio Status>  
 It shall be able to send the message(s):  
   <Set System Audio Mode>, <System Audio Mode Status>
```

So perhaps Apple's implementation is in line with the spec?

**Comment by SzymonSlupik** [comment]
I have also tested this with a Philips TV

After this exchange:
```
-> 05:7d audio mode?
<- 5f:7e audio status
```
the TV does not send any volume requests over the CEC bus.

But after this (responding with 72 to 7d):
```
-> 05:7d audio mode?
<- 5f:72 set audio
```

The TV remote V+/V- button presses are relayed to the CEC bus.

So the Philips implementation behaves identically to the Apple implementation.

**Comment by SzymonSlupik** [comment]
You are right, Thomas.

0x70 <System Audio Mode Request> is responded by 0x72 <Set System Audio Mode>
0x7d <Give System Audio Mode Status> is responded by 0x7e <System Audio Mode Status> 

I'm closing the issue - thanks for clarifying.
